language: node_js
node_js: node
script: yarn fix
branches:
  only:
  - master
  - "/v\\d\\./"
cache:
  directories:
  - node_modules

deploy:
  - provider: heroku
    app: adamgoldman-staging
    api_key:
      secure: NLs7zRVpv0jfkLYfnPO91pLntWLmSfRMPtjsVpY/5zT6IajaXROy/6pomBEGGvUYZuBTvjWvmlCmmL/xYZfqPlhW0R4I3fgvjygUmlXVzdxftjOmU3l675vMcaSPqqEo2KVN0whFtrtFqdR6f3vqUbkmRIfIpep89gqD2xO5xCTb13m94ijqE1PxAUu8l4y3sYraYC0YYAxHsuK9stHllY0MkyKxBrgbJQMKYhXKs3iqKK/F1A3+Hfs4FbCyQtyYh3/3bllPNjnTHEXtGyvbeo+iQPL+l41a5VOljJd+Bc7lBqtXrqfS99LN5XQy0sb4vvyKSw3LFftUbGM2UccwDmAchguKolsnX6zOQJ5uNXvl2XVxGCxqxYsSEW98dKNQ6LPtdDMQMWePr+RpdLbCjBRMgiSf/rwHCdMVxhtkb6NUDCRD1u+Q9hDhX7nRvPNbfxA5fAaIhl/XFYxqTG3+VKhX60X1sl0/7Ug8dRB1wM8berti+K438EaRh4CXssppAhfvE54Yf4ZzXN4e6W4iPSMEyGwI4o1Wl2voZjq81Ol1VG/ektosP8LnJF9ZctUkfQnILk3IpRoqWh84yRfS0dAKaYczpkhUEyUuu5FfeexKjfJzRElBkwxRDJkqKuhm9pMlAfOwbfXncK7icT5TUDEtW2yH7vIhIqJugLAI7MY=
  - provider: heroku
    app: adamgoldman
    api_key:
      secure: NLs7zRVpv0jfkLYfnPO91pLntWLmSfRMPtjsVpY/5zT6IajaXROy/6pomBEGGvUYZuBTvjWvmlCmmL/xYZfqPlhW0R4I3fgvjygUmlXVzdxftjOmU3l675vMcaSPqqEo2KVN0whFtrtFqdR6f3vqUbkmRIfIpep89gqD2xO5xCTb13m94ijqE1PxAUu8l4y3sYraYC0YYAxHsuK9stHllY0MkyKxBrgbJQMKYhXKs3iqKK/F1A3+Hfs4FbCyQtyYh3/3bllPNjnTHEXtGyvbeo+iQPL+l41a5VOljJd+Bc7lBqtXrqfS99LN5XQy0sb4vvyKSw3LFftUbGM2UccwDmAchguKolsnX6zOQJ5uNXvl2XVxGCxqxYsSEW98dKNQ6LPtdDMQMWePr+RpdLbCjBRMgiSf/rwHCdMVxhtkb6NUDCRD1u+Q9hDhX7nRvPNbfxA5fAaIhl/XFYxqTG3+VKhX60X1sl0/7Ug8dRB1wM8berti+K438EaRh4CXssppAhfvE54Yf4ZzXN4e6W4iPSMEyGwI4o1Wl2voZjq81Ol1VG/ektosP8LnJF9ZctUkfQnILk3IpRoqWh84yRfS0dAKaYczpkhUEyUuu5FfeexKjfJzRElBkwxRDJkqKuhm9pMlAfOwbfXncK7icT5TUDEtW2yH7vIhIqJugLAI7MY=
    on:
      tags: true
      all_branches: true