language: node_js
node_js: node
script: yarn fix
branches:
  only:
  - master
  - "/v\\d\\./"
cache:
  directories:
  - node_modules

deploy:
  - provider: heroku
    app: adamgoldman-staging
    api_key:
      secure: PUoxBRGFnTAz5Eo6zdmj7SRnagwsB03OcSd/rcbKjeOApQygAvhCbbo0W0s76zVJfU8yEsWEAs8GIvHQui0FwNDiDXBoifMD5BTT6ITgjlECK6cVEgB0EqzxBb93qsTouxy9CRF8uZ4dgGkNsiff8NFkHiEuLbIY90WYxkJerST80qTcpWus9qrgbQH/nGEFhPSM04FAllM9LpQJkXNrUODONCfj9VUEKXNoRQ1X1IASCcbkLL23dv6uK+tywurw3ivSMaGQ+371KIMJZVGbjDF/5nd+bYQep8NtW3C35W1IV0bOlflaoaNF7gzd5dw8BlPTfGAAtJ7PdnOZtIiAtvqp2XbbNuTQwisF4z0MXtg9oY5+3YLsoMoImm3lf39vrDlDB4PDLybxOESck4OPXcSYkgKehQdmqjNcEJJvQraQngkh/Fw3k7DysyrGUM+kbtcHkEWLWKnWClqRQCLu/sWQfk+TAlYVuV5ARcq9iUjLBNpt7VYNS8tvEIEw4rSkQIt17jeUPpWPu1eNx6hO/lBkMJlLCHLCr37GdzZ3uiuRM50HBeY7epoKGsM1khcdZ7kvrl6r2RI02oZ5Rfagk7fxCjzByAJD2ZbCu/IEkAcXu3I9kXYer4AQ+q58QACri41TqJr2YOepCG65JPXR5vFyifKgjrjg7jaevmjVAJY=
  - provider: heroku
    app: adamgoldman
    api_key:
      secure: PUoxBRGFnTAz5Eo6zdmj7SRnagwsB03OcSd/rcbKjeOApQygAvhCbbo0W0s76zVJfU8yEsWEAs8GIvHQui0FwNDiDXBoifMD5BTT6ITgjlECK6cVEgB0EqzxBb93qsTouxy9CRF8uZ4dgGkNsiff8NFkHiEuLbIY90WYxkJerST80qTcpWus9qrgbQH/nGEFhPSM04FAllM9LpQJkXNrUODONCfj9VUEKXNoRQ1X1IASCcbkLL23dv6uK+tywurw3ivSMaGQ+371KIMJZVGbjDF/5nd+bYQep8NtW3C35W1IV0bOlflaoaNF7gzd5dw8BlPTfGAAtJ7PdnOZtIiAtvqp2XbbNuTQwisF4z0MXtg9oY5+3YLsoMoImm3lf39vrDlDB4PDLybxOESck4OPXcSYkgKehQdmqjNcEJJvQraQngkh/Fw3k7DysyrGUM+kbtcHkEWLWKnWClqRQCLu/sWQfk+TAlYVuV5ARcq9iUjLBNpt7VYNS8tvEIEw4rSkQIt17jeUPpWPu1eNx6hO/lBkMJlLCHLCr37GdzZ3uiuRM50HBeY7epoKGsM1khcdZ7kvrl6r2RI02oZ5Rfagk7fxCjzByAJD2ZbCu/IEkAcXu3I9kXYer4AQ+q58QACri41TqJr2YOepCG65JPXR5vFyifKgjrjg7jaevmjVAJY=
    on:
      tags: true
      all_branches: true