language: node_js
node_js: node
script: yarn fix
branches:
  only:
  - master
  - "/v\\d\\./"
cache:
  directories:
  - node_modules

deploy:
  - provider: heroku
    app: adamgoldman-staging
    api_key:
      secure: QLfx2/olNc298Ia02M59hdCwUmD5Franm/vXBHnY8i/n6pPA4OBE4rTdwaiqC4tRTLuH8qi2VIllY8nofQ/BIvk9OERJXC09jKXy3fMenOKdXsK4BvzAQ/7Ex2FqYK4cV7GcpHJFVfs+gpLyaWCHOnbFZxHVO3u0Nv3Yzx+r+5iesMrgGzWsH1mhm70vwTHhj6tPRjTE5MkfhxVjaYbj8Fq1DArzIFEH8OSbmaRipC5GBFG0h8PXaxo3SoYE57Sja+9ZRZAs4our6rkw/nevYIrtZ2dIK21CZRzdbtLRWzBNbngO8/MNKfFcc9uXjYgksr1/6ibJlNS+WIShvfgRKj6dxtSUS70GuSdYBRg+NxfA5I3hJFaDxDnKVIL6S6Xv0fbvWdmKCUlc/gb2k9ZQQ79CKWskFUe3Sc+nk6LpXg81Ru2EHDjpGbOFty8+nTQVLQs4wfveSKHBBG8EAaCwjJNtEQ6Tg9YUoFmbCfzTseTBYTcoCwADzm1giCMD7Mlq6TDrkCpjO5xzrqAmQGZZr0Yso/4rK0ISYaHCboQ2DGonoIxKW/GdJFkT0pCbB6GEGVVOOJALzh2ZrZRsag6N6F2mmwCXkwQ+PtoPXT3L7jtJXBvH1plnsqahguMIOUgryp28pt8qTzEymepQDa1iw7wXUxQeXc29iQrEFyiOkm0=
  - provider: heroku
    app: adamgoldman
    api_key:
      secure: QLfx2/olNc298Ia02M59hdCwUmD5Franm/vXBHnY8i/n6pPA4OBE4rTdwaiqC4tRTLuH8qi2VIllY8nofQ/BIvk9OERJXC09jKXy3fMenOKdXsK4BvzAQ/7Ex2FqYK4cV7GcpHJFVfs+gpLyaWCHOnbFZxHVO3u0Nv3Yzx+r+5iesMrgGzWsH1mhm70vwTHhj6tPRjTE5MkfhxVjaYbj8Fq1DArzIFEH8OSbmaRipC5GBFG0h8PXaxo3SoYE57Sja+9ZRZAs4our6rkw/nevYIrtZ2dIK21CZRzdbtLRWzBNbngO8/MNKfFcc9uXjYgksr1/6ibJlNS+WIShvfgRKj6dxtSUS70GuSdYBRg+NxfA5I3hJFaDxDnKVIL6S6Xv0fbvWdmKCUlc/gb2k9ZQQ79CKWskFUe3Sc+nk6LpXg81Ru2EHDjpGbOFty8+nTQVLQs4wfveSKHBBG8EAaCwjJNtEQ6Tg9YUoFmbCfzTseTBYTcoCwADzm1giCMD7Mlq6TDrkCpjO5xzrqAmQGZZr0Yso/4rK0ISYaHCboQ2DGonoIxKW/GdJFkT0pCbB6GEGVVOOJALzh2ZrZRsag6N6F2mmwCXkwQ+PtoPXT3L7jtJXBvH1plnsqahguMIOUgryp28pt8qTzEymepQDa1iw7wXUxQeXc29iQrEFyiOkm0=
    on:
      tags: true
      all_branches: true